apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowci-minio
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flowci-minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flowci-minio
    spec:
      containers:
        - name: flowci-minio
          image: quay.io/minio/minio:RELEASE.2023-12-02T10-51-33Z
          env:
            - name: "MINIO_ROOT_USER"
              value: {{ .Values.minio.auth.rootUser }}
            - name: "MINIO_ROOT_PASSWORD"
              value: {{ .Values.minio.auth.rootPassword }}
          command: ["minio", "server", "/data", "--console-address", ":9090"]
          volumeMounts:
            - mountPath: "/data"
              name: data
          ports:
            - name: tcp
              containerPort: 9000
              protocol: TCP
            - name: protal
              containerPort: 9090
              protocol: TCP
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: flowci-minio-data
