kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flowci-minio-data
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
