apiVersion: v1
kind: Service
metadata:
  name: flowci-minio
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: tcp
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: protal
  selector:
    app.kubernetes.io/name: flowci-minio
