kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flowci-zookeeper-data
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.zookeeper.persistence.size }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flowci-zookeeper-data-log
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.zookeeper.persistence.size }}