kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flowci-rabbitmq-data
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.rabbitmq.persistence.size }}
